"""empty message

Revision ID: 14d769180b45
Revises: 
Create Date: 2021-09-08 20:12:47.059722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d769180b45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.String(length=256), nullable=True),
    sa.Column('to_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=True)
    op.create_table('vertices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('iter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vertices_id'), 'vertices', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vertices_id'), table_name='vertices')
    op.drop_table('vertices')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    # ### end Alembic commands ###
